//Date
let myDate = new Date()
//console.log(myDate.toLocaleDateString())
//console.log(myDate.toDateString())
//console.log(myDate.toISOString())
//console.log(myDate.toLocaleString())
//console.log(myDate.toTimeString())
let myCreatedDate = new Date(2024, 3, 28, 9, 20)
//console.log(myCreatedDate.toLocaleString())
//console.log(myCreatedDate.getTime())
//console.log(Math.floor(Date.getTime/1000))
let newDate = new Date()
console.log(newDate.getDay())
console.log(newDate.getTime())
